
site_name: Yu Li

site_url: https://Skylanding.github.io/

theme:
  name: material
  language: en

copyright: 'This website was stolen from my <a href="https://maechd.github.io/">best friend</a>'

plugins:
  - search:
      lang: [en, zh]
  - i18n:
      # 不要写 default_language
      languages:
        - locale: en
          name: English
          default: true      # 用这个来指定默认语言
        - locale: zh
          name: 简体中文
      docs_structure: folder
      reconfigure_material: true

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.mark       # ← 新增，可用 ==text== 语法


nav:
  - Home: index.md   # i18n 插件会自动在 docs/en/ 与 docs/zh/ 下找 index.md

extra_css:
  - assets/site.css 

extra_javascript:
  # - https://unpkg.com/leaflet@1.9.4/dist/leaflet.js  <-- 已删除
  # - assets/map.js                                  <-- 已删除
